### ISSUE TITLE
how to add public transport stop positions?

### ISSUE THREAD

**Issue by prototype99** [bwr57/CustomizePublicTransportStop#9] opened 2019-03-15 23:49 UTC
youtube video makes it look super simple, but the option to add stop position isn't there and when i click save on customise... it doesn't make one automatically

**Comment by sophietheopossum** [comment] 2019-03-16 11:54
well i have since found that add stop position has moved to the left pane, but i still can't find how to make it automatically like in the video, or how to automatically make the stop area relation

**Comment by bwr57** [comment] 2019-03-18 07:20
Dear @prototype99, thank you for your question.

Which is the youtube video? I didn't make any video about this plugin. 

About your question. Yes, this plugin create the stop position point and the stop area relation automatically. It is its main target. Usually you need to create new or select existing point of a transport waiting, press "u" key or select menu item, fill the fields in the dialog window and press "Customize" button. You can use the node for mapping of the simple transport waiting point (such as bus stop) or the way for mapping of the big object (such as railway platform). In the last case, the plugin calculate the center of the platform as the point for a calculation of the stop point position. The stop position location is calculated as nearest point on the nearest applicable way. 
I used this plugin for creation or transforming to PTv2 standard about 95 % stops in the Ekaterinburg city and its suburbs and I can say that your problem is rare really. I recommend you to check next issues:
1. The plugin demand the road way for a public transport moving for a calculation of the stop position. You must download this way into the editor from OSM server (or create it in the current JOSM session) before you call plugin. In the real live, this problem is possible at editing of the long distance routes or railroads. The JOSM download the way when at least one its node is in the download area, and this node can be in the few kilometers from the stop position. You must find it and download the road way.
2. The road way must be applicable for a moving of the selected type of a public transport. It is necessary for excluding of the all other ways, such the buildings, barriers, zone boundaries, at cetera. The plugin check the tag values of the way and use for creation of the stop position only applicable ways. Therefore, the road must have the next tag values: for buses/trolleybuses/shared taxi - highway=<trunk, trunk_link, primary, primary_link, secondary, secondary_link, tertiary, tertiary_link, unclassified, residential, road, service, bus_guideway>, for trams - railway=tram, for trains - railway=rail+usage=main. Check the tag values of your road way and setup way, if it necessary.
3. The plugin use for calculation of the stop position only nearest ways in the radius of 200 pixels from the transport waiting position. The real distance depend from the scale of the map. You can move the transport waiting position near to the road way or change a map scale and find the position for reliable creation of the stop position. After you can move the transport waiting position and the stop position to its real location. Remember, that all settings are saved in the tag set of the transport waiting position node or way and download into the dialog window when you select this object and call plugin. And the plugin try create the stop position node and the stop area relation, if it are not exists, at every pressing of the "Customize" button. It is very useful for transforming of the stop descriptions from PTv1 to PTv2 standard. You can setup, for example, bus stop or platform, move it, change map scale, change the road tags and so on and try to create the stop position by plugin again. All settings will be readied from the bus stop characteristics and you must not input its again.
This are main possible causes of your problem and the methods for its resolving. Additionally:
4. The feature (or bug) of this soft is that it try use the existing nodes in the road way to define the stop position instead of creating new node. When I wrote this plugin, I think, that it is good idea. But at the real using, it can create the problem. For the Russian conditions the next situation is exists: the two bus stops on the different sides of the road and the crossing between. The plugin can use the crossing node as the stop position node instead of creation of the new stop position node. In this case, you can revert changes (Ctrl-Z), move stop bus far from the crossing and try again and after move the bus stop back.
In addition, you can give me the reference on the stop and road, where this plugin is not work properly. I will try to check the situation at near future.

Best regards
Rodion

**Comment by sophietheopossum** [comment] 2019-03-19 11:06
i tried to follow https://youtu.be/OcS8-g1EGfk which was referenced at https://wiki.openstreetmap.org/wiki/JOSM/Plugins/CustomizePublicTransportStop .

however... this time... it worked? i'm not sure what was wrong last time, so i will do it again, i guess. 

would you be open to me making a pull request with guides on what to do in various situations though? my area's public transport is in... varying degrees of quality, so it would be an ideal way for me to make documentation based on real data. i would add it to the readme.md so that people see it the moment they open this repository, and maybe also on the wiki page after the pull request is accepted. 

i'm not sure what i done differently... but i guess with documentation perhaps (?) i wouldn't have ran into the problem. so i feel that may be the best way to ensure this issue won't need to be reopened by anyone.

**Comment by bwr57** [comment] 2019-03-20 06:56
![Selection transport type](https://user-images.githubusercontent.com/5475691/54667146-76205800-4b0d-11e9-9c0b-c4d2bd897576.png)

Dear @prototype99 .

Thank you for the info about video. It isn't my art :) I didn't know about it early. But this video is more less proper. Main moment - you don't need to use special plugin "Add stop position" to create the node for mapping the waiting place. Moreover, this is error. The stop position node must be the part of the way corresponding to the road using by the public transport. But my plugin check this situation and fix this bug automatically. So you need install one new node (or select existing) near the road way and press "u" key. Also you can draw the line (way) if you want show the platform on the map and press "u" key, All tags will assign to the this node or way automatically.

I checked the last version of the plugin uploaded on the Github and version downloaded by JOSM from its repository. Both versions are working properly. In the test area plugin created bus stop, bus station, tram stop and railroad station with stop positions and stop areas using node and way for a mapping of the waiting place. So, I think that you forget to select a transport type (bus, tram, train, etc). The plugin use this setting for searching of the road way. Or you installed this node far from the road way. 

The problem of the documentation is exists of couse. The cause is my bad English. In this plugin I maked two errors only. Plugin didn't check that the user didn't select any node or way before call. And the orphograpfic error in the word "shelter". The users raped all my brain by the this orphografic error :) I think, that in the manual such errors will more. Therefore I wrote more less detailed Russian manual but in the English version wrote a main info about plugin only. If you will help me to make the English version of the manual more less readable, I'll be thanked very much.

If it isn't secret, what is the area where you used this plugin. I tested it in the Russian conditions only and I interest, how is it working in the other conditions.

Thank you!

Best regards
Rodion

**Comment by sophietheopossum** [comment] 2019-03-20 07:59
yeah i think it may have been too far. i think perhaps it could help, if there was an option to place the stop position on the selected way? so if i select the bus stop and a way, it places the stop position on that way.

the area i'm working on is Peterborough, England. if you follow the tagging list you may soon see a link to it, we're thinking about ways to make route relations easier to maintain. so once i'm sure they can't see problems in the route i will make an example for the new idea for comparison. it seems to do fine in these conditions as well which is nice

**Comment by bwr57** [comment] 2019-03-20 10:50
Dear @prototype99 ,

how I understand, was bus stops Ashleigh, Rangefield , etc edited by this plugin and it is working? 

The idea to select the waiting point node and the road way was declined becouse the plugin must be maximum simple for user and allow to create the complex stop areas with the several platforms in the future. And the current algoritm work in the 99 % of the cases. 

For maintaining of the routes I tried to develop other project, but it is not ready now. But I will glad to read the your ideas.

Best regards
Rodion

**Comment by sophietheopossum** [comment] 2019-03-20 11:32
yes, that is correct, later i will test transport in osmand

**Closed as completed** 2019-12-20 08:58 UTC
